spring:
  datasource:
    url: metro.proxy.rlwy.net:55551
    username: postgres
    password: ggAISIteUcANVHsEYMXObJKChLeEaciX
    driver-class-name: org.postgresql.Driver
  application:
    name: pushup
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
cors-policies: chrome-extension://eipdnjedkpcnlmmdfdkgfpljanehloah, http://localhost:3000, http://localhost:8080, http://[::1]:3000/, https://push-up-5wnph8og8-matyivans-projects.vercel.app/, https://push-up-web.vercel.app/