spring:
  datasource:
    username: sa
    url: jdbc:h2:file:./data/pushupdb
    driverClassName: org.h2.Driver
    password: pa
  h2:
    console:
      enabled: 'true'
  application:
    name: pushup
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
cors-policies: chrome-extension://eipdnjedkpcnlmmdfdkgfpljanehloah, http://localhost:3000, http://localhost:8080, http://[::1]:3000/